### ISSUE TITLE
Roam Portal does not open

### ISSUE THREAD

**Issue by 8bitgentleman** [dkapila/Roam-Portal#1]
After setting the hotkey to open roam portal hitting the hotkey does not do anything. In the console I get this error
![image](https://user-images.githubusercontent.com/4028391/230625454-dbd98664-641f-4380-9ab3-effd0b8d2a42.png)

**Comment by dkapila** [comment]
It seems like Roam Portal is not being initialized correctly.

1. Does this happen in the browser and the desktop app?
2. Can you try to disable other (Roam/Chrome) extensions?

**Comment by 8bitgentleman** [comment]
This was happening on both desktop and browser. Interestingly disabling all extensions, enabling Roam Portal, then re-enabling the other extension made RP load correctly. Even loads correctly on refresh now. Very strange
