### ISSUE TITLE
Roam Portal: Icon not showing up

### ISSUE THREAD

**Issue by mike-leber** [dkapila/Roam-Portal#2]
When I enable Roam Portal the icon does not show. It only shows, when I go to the Roam Depot setting and disable / enable Roam Portal. Next page refresh, the icon will be gone again.

This happens on MacOS with Chrome and Safari, both latest versions.

**Comment by dkapila** [comment]
Can you confirm if this happens in the Roam electron app as well? I wonder if it's due to another extension/css change?

Also, are there any errors in the console log (in chrome developer tools)?

**Comment by mike-leber** [comment]
It does not seem to happen in the Roam mobile app, just that the screen with its current setting is quite useless on a phone.

I deactivated all extra css and also all other Roam Depot plugins.

Did not improve.

**Comment by dkapila** [comment]
I meant not the mobile app, but the Roam Desktop Electron app. Does it repro in there as well? Because if it does, then it is more likely an issue with Roam Portal. Secondly - can you double check if there are any error logs (Cmd + Opt + J in Chrome to see the console logs)

So far I have not had this issue, or also heard from anyone else about it - so I would need to find a way to repro it. 
 
There is also another Roam extension which allows someone to hide this Icon if they don't want it (although it seems like you are not running it)

![CleanShot 2023-05-16 at 12 24 54@2x](https://github.com/dkapila/Roam-Portal/assets/1458980/4dcb7641-e61e-46d9-a826-6f14742c923f)

**Comment by mike-leber** [comment]
The issue does not happen in the desktop app - there the icon properly shows up.


But Chrome reports quite a few errors

**Comment by dkapila** [comment]
Could you paste those errors from the log?

**Comment by mike-leber** [comment]
main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:9235 false
DevTools failed to load source map: Could not load content for https://roamresearch.com/js/compiled/main.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4783 2023-05-16T12:06:40.190Z INFO [relemma.core:288] - Roam version 0.9.11-98f46a8a
DevTools failed to load source map: Could not load content for https://roamresearch.com/js/compiled/route-app.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for chrome-extension://kgkmjbhbdakcdfkkgmmihcceekcdmefe/app.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
instrument.ts:132 Intercom boot run
frame-modern.147d25d0.js:1 Intercom Messenger warning: Identity Verification is set up correctly but not enabled. For details on how to enable it, see https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-on-your-web-product.
n @ frame-modern.147d25d0.js:1
ae @ frame-modern.147d25d0.js:1
(anonymous) @ frame-modern.147d25d0.js:1
await in (anonymous) (async)
(anonymous) @ vendor-modern.77b49a51.js:2
createOrUpdateUser @ frame-modern.147d25d0.js:1
createOrUpdateUser @ frame-modern.147d25d0.js:1
r @ frame-modern.147d25d0.js:1
boot @ frame-modern.147d25d0.js:1
(anonymous) @ frame-modern.147d25d0.js:1
HAa @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4728
q @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4740
v @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4743
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4604
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4604
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:9002
Exa @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4596
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:3898
frame-modern.147d25d0.js:1 Intercom Messenger warning: Identity Verification is set up correctly but not enabled. For details on how to enable it, see https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-on-your-web-product.
n @ frame-modern.147d25d0.js:1
ae @ frame-modern.147d25d0.js:1
(anonymous) @ frame-modern.147d25d0.js:1
await in (anonymous) (async)
(anonymous) @ vendor-modern.77b49a51.js:2
createOrUpdateUser @ frame-modern.147d25d0.js:1
createOrUpdateUser @ frame-modern.147d25d0.js:1
update @ frame-modern.147d25d0.js:1
(anonymous) @ frame-modern.147d25d0.js:1
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4728
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4745
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4736
Nf @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1286
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1254
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1263
md @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1064
ig @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1016
Af @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1016
tg @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1021
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1018
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1136
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1136
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1106
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1106
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1103
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1094
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1095
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:1092
instrument.ts:132 load hide left sidebar button plugin
instrument.ts:132 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
(anonymous) @ instrument.ts:132
(anonymous) @ 775311ac-50ce-4242-bc25-870a66053a14:2
(anonymous) @ 775311ac-50ce-4242-bc25-870a66053a14:2
instrument.ts:132 Find & replace loaded.
instrument.ts:132 load tweet extract plugin
DevTools failed to load source map: Could not load content for https://roamresearch.com/js/compiled/app-graph.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
instrument.ts:132 WARNING: Multiple instances of Three.js being imported.
(anonymous) @ instrument.ts:132
(anonymous) @ d9d2d0ad-af47-49e7-b44a-ed97b1999995:28917
frame-modern.147d25d0.js:1 Intercom Messenger warning: Identity Verification is set up correctly but not enabled. For details on how to enable it, see https://docs.intercom.com/configure-intercom-for-your-product-or-site/staying-secure/enable-identity-verification-on-your-web-product.
n @ frame-modern.147d25d0.js:1
ae @ frame-modern.147d25d0.js:1
(anonymous) @ frame-modern.147d25d0.js:1
await in (anonymous) (async)
(anonymous) @ vendor-modern.77b49a51.js:2
createOrUpdateUser @ frame-modern.147d25d0.js:1
createOrUpdateUser @ frame-modern.147d25d0.js:1
update @ frame-modern.147d25d0.js:1
(anonymous) @ frame-modern.147d25d0.js:1
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4728
Ahc @ route-app.js:1825
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4130
Hka @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4130
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4136
oka @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4121
Dka @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4128
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4136
xe @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:331
we @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:330
Ko @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:452
Jj @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:384
Kj @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:384
Jg @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:377
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:280
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:210
rh @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:279
gi @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:279
Sh @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:279
Bg @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:372
enqueueForceUpdate @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:436
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:197
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8461
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8460
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8460
a @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8460
requestAnimationFrame (async)
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8460
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8475
xka @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4126
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4122
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8466
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:8467
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:7219
$U @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:7218
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:7396
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:5351
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:7392
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4038
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:7396
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4934
wI @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4935
C @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:5377
D @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:5399
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4604
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4604
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:9002
Exa @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:4596
(anonymous) @ main.js?__WB_REVISION__=f90aac5a7458169e67015faeb38d7f8b:3898
instrument.ts:132 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
(anonymous) @ instrument.ts:132
(anonymous) @ b5c3368d-ada8-4294-acd9-ddaefe6f17e7:2
(anonymous) @ b5c3368d-ada8-4294-acd9-ddaefe6f17e7:2
instrument.ts:132 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
(anonymous) @ instrument.ts:132
(anonymous) @ 72e68c53-6a12-4510-b16e-3cd2064b4b7c:2
(anonymous) @ 72e68c53-6a12-4510-b16e-3cd2064b4b7c:2
instrument.ts:132 {panel: {…}, set: ƒ, get: ƒ, getAll: ƒ}
instrument.ts:132 Page references counter extension loaded.
instrument.ts:132 @babel/polyfill is loaded more than once on this page. This is probably not desirable/intended and may have consequences if different versions of the polyfills are applied sequentially. If you do need to load the polyfill more than once, use @babel/polyfill/noConflict instead to bypass the warning.
(anonymous) @ instrument.ts:132
(anonymous) @ 9e5ceaaa-746f-4301-a125-f2ccde1500a0:2
(anonymous) @ 9e5ceaaa-746f-4301-a125-f2ccde1500a0:2
instrument.ts:132 load clear sidebar plugin

**Comment by dkapila** [comment]
From this line it seems you have the Roam Portal chrome extension installed (or it is still cached somehow). Could you remove that and just use the one in the Roam Depot? 

![CleanShot 2023-05-16 at 15 09 41@2x](https://github.com/dkapila/Roam-Portal/assets/1458980/1f062b22-c312-4515-8b4c-eb8f0bf04709)

**Comment by dkapila** [comment]
I've also chatted with @abhayprasanna who mentioned that there are some issues with the Roam Depot itself that maybe causing the issue.

**Comment by mike-leber** [comment]
That was it! Thanks so much!
Problem solved.

**Comment by mike-leber** [comment]
btw: a nice feature would be to filter „Log days“ from the graph.
The only feature, that’s included with the standard Roam Graph Overview (which as such is visually not useful)

**Comment by dkapila** [comment]
Yes, will look into adding a filter for Log Days :)

**Comment by mike-leber** [comment]
That would be super helpful.

Daily logs fill a lot of references. So graphs get cluttered.

But for navigating content, they do not play a big role.
